### ISSUE TITLE
大佬我想问下票星球那个脚本为啥一直提示异常

### ISSUE THREAD

**Issue by axiliya2568** [Youthux/wanjuwa#4]
![IRU8 1{1Q6 I(24 A~5{P5U](https://github.com/Youthux/wanjuwa/assets/139161227/f387458d-0dcf-4dcf-aaa1-cc9e49341c20)

**Comment by Youthux** [comment]
是不是没填观演人信息

**Comment by Youthux** [comment]
> ![IRU8 1{1Q6 I(24 A~5{P5U](https://user-images.githubusercontent.com/139161227/257042874-f387458d-0dcf-4dcf-aaa1-cc9e49341c20.png)

是不是没填观演人信息

**Comment by axiliya2568** [comment]
![06R}1(O6PF `C{UOY6$ 3LS](https://github.com/Youthux/wanjuwa/assets/139161227/488f7d47-a600-464f-9fa1-d9e5f320f248)
填了呀，但一直提示证件信息不足

**Comment by axiliya2568** [comment]
希望大佬指点下
![JC7T~ %J3J%U)CCO@KMIG4O](https://github.com/Youthux/wanjuwa/assets/139161227/7565f2b5-0e27-4b4e-b87a-073b03f26015)

**Comment by Youthux** [comment]
> 希望大佬指点下 ![JC7T~ %J3J%U)CCO@KMIG4O](https://user-images.githubusercontent.com/139161227/257043504-7565f2b5-0e27-4b4e-b87a-073b03f26015.png)

request.py  用294行替换掉254-259行

**Comment by axiliya2568** [comment]
> > 希望大佬指点下 ![JC7T~ %J3J%U)CCO@KMIG4O](https://user-images.githubusercontent.com/139161227/257043504-7565f2b5-0e27-4b4e-b87a-073b03f26015.png)
> 
> request.py 用294行替换掉254-259行

大佬牛逼，可以了谢谢谢

**Comment by axiliya2568** [comment]
> > 希望大佬指点下 ![JC7T~ %J3J%U)CCO@KMIG4O](https://user-images.githubusercontent.com/139161227/257043504-7565f2b5-0e27-4b4e-b87a-073b03f26015.png)
> 
> request.py 用294行替换掉254-259行

大佬有没有vx我加你给你发个红包谢谢

**Comment by Youthux** [comment]
> > > 希望大佬指点下 ![JC7T~ %J3J%U)CCO@KMIG4O](https://user-images.githubusercontent.com/139161227/257043504-7565f2b5-0e27-4b4e-b87a-073b03f26015.png)
> > 
> > 
> > request.py 用294行替换掉254-259行
> 
> 大佬有没有vx我加你给你发个红包谢谢

不用
